orangehrm/orangehrm

symfony/lib/composer.json
symfony/plugins/orangehrmCorePlugin/lib/dao/MenuDao.php
symfony/plugins/orangehrmCorePlugin/test/authorization/dao/MenuDaoTest.php
symfony/plugins/orangehrmCorporateDirectoryPlugin/test/model/wrapper/CorporateDirectoryWebServiceWrapperTest.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Pim/EmployeeContactDetailAPI.php
symfony/plugins/orangehrmRESTPlugin/test/api/admin/entity/ApiUserTest.php
symfony/plugins/orangehrmRESTPlugin/test/api/pim/ApiEmployeeContactDetailAPITest.php
symfony/plugins/orangehrmRESTPlugin/test/api/pim/ApiEmployeeEducationAPITest.php
symfony/plugins/orangehrmRESTPlugin/test/api/pim/entity/ApiEmployeeTest.php

These changes do not have any PHP7 related changes.
But note that the require-dev for phpunit 5.7 results in phpunit warnings. However, the warnings do not cause the tests to fail.

Fixed unit tests. Now all unit tests are passing in travis

---

upgrader/apps/upgrader/lib/filter/ActionFilter.php

redirect to login if system is already installed

---

symfony/plugins/orangehrmRESTPlugin/doc/18-delete-employee-supervisor-detail-end-point.php

annotation changed in supervisor API doc

API:doc supervisor mandatory fields annotation changes

---

README.md

updated the demo URL

---

symfony/apps/orangehrm/i18n/messages.zz_ZZ.xml
symfony/apps/orangehrm/lib/message/ValidationMessages.php
symfony/plugins/orangehrmAdminPlugin/modules/admin/actions/saveSystemUserAction.class.php
symfony/plugins/orangehrmAdminPlugin/modules/admin/templates/saveSystemUserSuccess.php

Usability Improvement on Add User

OHRM 10 : Usability Improvement on Add User

---

symfony/plugins/orangehrmLeavePlugin/web/js/assignLeaveSuccess.js

Leave is assigned as half day when specific time option is choosen for "End Day - Partial Day" option

OHRM-19: Leave is assigned as half day

---

dbscript/dbscript-2.sql
upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask67.php
upgrader/apps/upgrader/lib/utility/UpgradeUtility.php

OHRM-85: Admin employee cannot define time sheet period

---

installer/config.ini

Jenkins was unable to run unit tests.

OHRM-config: updating credentials

---

installer/config.ini

Reverts orangehrm/orangehrm#287

Revert "OHRM-config: updating credentials"

---

dbscript/dbscript-2.sql
symfony/plugins/orangehrmAdminPlugin/lib/form/ModuleForm.php
symfony/plugins/orangehrmAdminPlugin/modules/admin/templates/viewModulesSuccess.php

OHRM-160 : Add SQL scripts to run in web installer and made maintenance module electable.

---

symfony/plugins/orangehrmLeavePlugin/lib/dao/LeaveRequestDao.php
symfony/plugins/orangehrmLeavePlugin/lib/service/LeaveRequestService.php
symfony/plugins/orangehrmLeavePlugin/modules/leave/actions/viewLeaveListAction.class.php

OHRM-139 : When include past employees in Leave Purge Employees leave record are comiing issue.

---

symfony/plugins/orangehrmCorePlugin/lib/mail/orangehrmMailTransport.php

OHRM-538: Fix sendmail email not sending issue

---

devTools/general/reinstall.php
devTools/general/reset-installation.php
devTools/installer/SOURCE/content/orangehrm2/symfony/config/databases.yml
devTools/load/general/load-employees.php
devTools/load/recruitment/load-candidates.php
install.php
installer/ApplicationSetupUtility.php
installer/BasicConfigurations.php
installer/cleanUp.php
upgrader/apps/upgrader/lib/utility/UpgradeUtility.php

OHRM-535: Define database connections charset

---

symfony/plugins/orangehrmRESTPlugin/doc/employee-leave-entitlement-end-point.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Leave/LeaveEntitlementAPI.php

OHRM-548 api: Made leaveType as optional in get leave entitlement endpoint

---

symfony/config/ProjectConfiguration.class.php

OHRM-547: Fix CSS break issue in login page

---

upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask66.php

OHRM-545 upgrader: Fix primary key issue in 4.1 upgrader task

---

symfony/apps/orangehrm/i18n/messages.en_US.xml
symfony/apps/orangehrm/i18n/messages.zz_ZZ.xml
symfony/plugins/orangehrmMarketPlacePlugin/lib/service/PublishAssetService.php

recreate since could not reopen #642

OHRM-612: Run publish assets without symfony task

---

apidoc.json
symfony/plugins/orangehrmCoreOAuthPlugin/modules/oauth/actions/baseOAuthAction.class.php
symfony/plugins/orangehrmRESTPlugin/config/orangehrmRESTPluginConfiguration.class.php
symfony/plugins/orangehrmRESTPlugin/config/routing.yml
symfony/plugins/orangehrmRESTPlugin/doc/employee-leave-requests-end-point.php
symfony/plugins/orangehrmRESTPlugin/doc/mobile/1-my-leave-entitlement-end-point.php
symfony/plugins/orangehrmRESTPlugin/doc/mobile/2-my-leave-request-end-point.php
symfony/plugins/orangehrmRESTPlugin/doc/search-leave-requests-end-point.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Leave/Entity/Leave.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Leave/Entity/LeaveBalance.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Leave/Entity/LeaveEntitlement.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Leave/Entity/LeaveRequest.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Mobile/Model/LeaveEntitlementModel.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Mobile/Model/LeaveRequestModel.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Mobile/MyLeaveEntitlementAPI.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Mobile/MyLeaveRequestAPI.php
symfony/plugins/orangehrmRESTPlugin/lib/Api/Model/ModelTrait.php
symfony/plugins/orangehrmRESTPlugin/modules/apiv1mobile/actions/BaseMobileApiAction.class.php
symfony/plugins/orangehrmRESTPlugin/modules/apiv1mobile/actions/MyLeaveEntitlementApiAction.class.php
symfony/plugins/orangehrmRESTPlugin/modules/apiv1mobile/actions/MyLeaveRequestApiAction.class.php
symfony/plugins/orangehrmRESTPlugin/modules/apiv1mobile/config/security.yml
symfony/plugins/orangehrmRESTPlugin/test/api/leave/entity/ApiLeaveBalanceEntityTest.php
symfony/plugins/orangehrmRESTPlugin/test/api/mobile/ApiMyLeaveEntitlementAPITest.php
symfony/plugins/orangehrmRESTPlugin/test/api/mobile/ApiMyLeaveRequestAPITest.php
symfony/plugins/orangehrmRESTPlugin/test/api/mobile/model/ApiLeaveEntitlementModelTest.php
symfony/plugins/orangehrmRESTPlugin/test/api/mobile/model/ApiLeaveRequestModelTest.php
symfony/plugins/orangehrmRESTPlugin/test/api/model/ModelTraitTest.php
symfony/plugins/orangehrmRESTPlugin/test/api/pim/ApiEmployeeSearchAPITest.php
symfony/plugins/orangehrmRESTPlugin/test/orangehrmRESTPluginAllTests.php

OHRM-729:Implement my-leave-requests API endpoint

---

symfony/client/src/core/util/composable/usePaginate.ts
symfony/client/src/orangehrmAdminPlugin/components/EmployeeDropdown.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/EditSystemUser.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/SaveSystemUser.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/SystemUser.vue

OHRM5X-29: System user filters API connected

---

symfony/client/src/orangehrmPimPlugin/components/EmploymentStatusDropdown.vue
symfony/client/src/orangehrmPimPlugin/components/JobtitleDropdown.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/Employee.vue

Employee status filter substituted with employment status filter

OHRM5X-164: PIM - Employee List Employment status filter added

---

symfony/client/src/core/styles/global.scss
symfony/client/src/orangehrmPimPlugin/components/EditAttachment.vue
symfony/client/src/orangehrmPimPlugin/components/EditEmergencyContact.vue
symfony/client/src/orangehrmPimPlugin/components/EditEmployeeLayout.vue
symfony/client/src/orangehrmPimPlugin/components/ProfileActionHeader.vue
symfony/client/src/orangehrmPimPlugin/components/SaveEmergencyContact.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeContactDetails.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeEmergencyContacts.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeePersonalDetails.vue
symfony/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php
symfony/plugins/orangehrmPimPlugin/Api/EmployeeContactDetailsAPI.php
symfony/plugins/orangehrmPimPlugin/Api/Model/EmployeeContactDetailsModel.php
symfony/plugins/orangehrmPimPlugin/Controller/EmployeeContactDetailsController.php
symfony/plugins/orangehrmPimPlugin/Controller/EmployeeEmergencyContactsController.php
symfony/plugins/orangehrmPimPlugin/config/routes.yaml

Additional commits:
- Contact details API integration
- Attachment FE Changes

OHRM5X-114: PIM - Emergency contact screens 

---

symfony/plugins/orangehrmPimPlugin/Api/EmpEmergencyContactAPI.php
symfony/plugins/orangehrmPimPlugin/Api/Model/EmpEmergencyContactModel.php
symfony/plugins/orangehrmPimPlugin/Dao/EmpEmergencyContactDao.php
symfony/plugins/orangehrmPimPlugin/Dto/EmpEmergencyContactSearchFilterParams.php
symfony/plugins/orangehrmPimPlugin/Service/EmpEmergencyContactService.php
symfony/plugins/orangehrmPimPlugin/config/routes.yaml
symfony/plugins/orangehrmPimPlugin/entity/Decorator/EmpEmergencyContactDecorator.php
symfony/plugins/orangehrmPimPlugin/entity/EmpEmergencyContact.php
symfony/plugins/orangehrmPimPlugin/entity/Employee.php
symfony/plugins/orangehrmPimPlugin/test/Dao/EmpEmergencyContactDaoTest.php
symfony/plugins/orangehrmPimPlugin/test/Entity/EmpEmergencyContactTest.php
symfony/plugins/orangehrmPimPlugin/test/Service/EmpEmergencyContactServiceTest.php
symfony/plugins/orangehrmPimPlugin/test/fixtures/EmpEmergencyContactDao.yml
symfony/plugins/orangehrmPimPlugin/test/fixtures/EmployeeDao.yml

updated routes.yaml
added t pagination, sorting to the API
added service Test cases

Ohrm5 x 190: PIM - Emergency Contacts - BE

---

symfony/client/src/components.ts
symfony/client/src/core/components/required/RequiredText.vue
symfony/client/src/orangehrmAdminPlugin/pages/employmentStatus/EditEmploymentStatus.vue
symfony/client/src/orangehrmAdminPlugin/pages/employmentStatus/EmploymentStatus.vue
symfony/client/src/orangehrmAdminPlugin/pages/employmentStatus/SaveEmploymentStatus.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobCategory/EditJobCategory.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobCategory/JobCategory.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobCategory/SaveJobCategory.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobTitle/EditJobTitle.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobTitle/JobTitle.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobTitle/SaveJobTitle.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationEducation/EditQualificationEducation.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationEducation/QualificationEducation.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationEducation/SaveQualificationEducation.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationLanguage/EditQualificationLanguage.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationLanguage/QualificationLanguage.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationLanguage/SaveQualificationLanguage.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationLicense/EditLicense.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationLicense/License.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationLicense/SaveLicense.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationMembership/EditQualificationMembership.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationMembership/QualificationMembership.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationMembership/SaveQualificationMembership.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationSkill/EditQualificationSkill.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationSkill/QualificationSkill.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationSkill/SaveQualificationSkill.vue
symfony/plugins/orangehrmAdminPlugin/Dto/EmploymentStatusSearchFilterParams.php
symfony/plugins/orangehrmAdminPlugin/Dto/SkillSearchFilterParams.php

Fixed  common bugs in admin Qualification screens and Job screens

OHRM5X-69 : Fixed  common bugs in admin Qualification screens and Job screens

---

symfony/plugins/orangehrmAdminPlugin/Api/JobTitleAPI.php
symfony/plugins/orangehrmAdminPlugin/entity/JobTitle.php
symfony/plugins/orangehrmCorePlugin/Api/V2/CollectionEndpoint.php
symfony/plugins/orangehrmCorePlugin/Api/V2/EndpointCollectionResult.php
symfony/plugins/orangehrmCorePlugin/Api/V2/EndpointResourceResult.php
symfony/plugins/orangehrmCorePlugin/Api/V2/EndpointResult.php
symfony/plugins/orangehrmCorePlugin/Api/V2/ResourceEndpoint.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Serializer/AbstractEndpointResult.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Serializer/EndpointDeleteResult.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Serializer/EndpointGetAllResult.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Serializer/EndpointGetOneResult.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Serializer/EndpointUpdateResult.php

<br />
<hr />
<br />
<br />
<hr />
<br />
<br />
<hr />
<br />
<br />
<hr />
<br />
<hr />
<br />
<br />
<hr />
Model approach and Validation rules approach not changed

OHRM5X-92:Restructure REST V2 APIs

---

installer/dbscript/dbscript-2.sql
phpunit.xml
symfony/client/src/orangehrmAdminPlugin/pages/employmentStatus/EditEmploymentStatus.vue
symfony/client/src/orangehrmAdminPlugin/pages/employmentStatus/SaveEmploymentStatus.vue
symfony/client/src/orangehrmAdminPlugin/pages/nationality/EditNationality.vue
symfony/client/src/orangehrmAdminPlugin/pages/nationality/Nationality.vue
symfony/client/src/orangehrmAdminPlugin/pages/nationality/SaveNationality.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationMembership/QualificationMembership.vue
symfony/client/src/pages.ts
symfony/plugins/orangehrmAdminPlugin/Api/EducationAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/LanguageAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/LicenseAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/MembershipAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/Model/NationalityModel.php
symfony/plugins/orangehrmAdminPlugin/Api/NationalityAPI.php
symfony/plugins/orangehrmAdminPlugin/Controller/NationalityController.php
symfony/plugins/orangehrmAdminPlugin/Controller/SaveNationalityController.php
symfony/plugins/orangehrmAdminPlugin/Dao/NationalityDao.php
symfony/plugins/orangehrmAdminPlugin/Dto/NationalitySearchFilterParams.php
symfony/plugins/orangehrmAdminPlugin/Service/NationalityService.php
symfony/plugins/orangehrmAdminPlugin/config/routes.yaml
symfony/plugins/orangehrmAdminPlugin/test/Api/NationalityAPITest.php
symfony/plugins/orangehrmAdminPlugin/test/Dao/NationalityDaoTest.php
symfony/plugins/orangehrmAdminPlugin/test/Entity/EducationTest.php
symfony/plugins/orangehrmAdminPlugin/test/Entity/LanguageTest.php
symfony/plugins/orangehrmAdminPlugin/test/Entity/LicenseTest.php
symfony/plugins/orangehrmAdminPlugin/test/Entity/MembershipTest.php
symfony/plugins/orangehrmAdminPlugin/test/Service/NationalityServiceTest.php
symfony/plugins/orangehrmPimPlugin/Controller/EmployeePersonalDetailController.php

OHRM5X-186 : Admin - Nationalities

---

symfony/client/src/core/plugins/loader/loader.scss
symfony/client/src/core/plugins/loader/loader.ts
symfony/client/src/main.ts
symfony/client/src/orangehrmPimPlugin/components/EditEmployeeLayout.vue
symfony/client/src/orangehrmPimPlugin/components/SaveTermination.vue
symfony/client/src/orangehrmPimPlugin/components/TerminateModal.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/employee.scss
symfony/plugins/orangehrmPimPlugin/Api/EmployeeTerminationAPI.php
symfony/plugins/orangehrmPimPlugin/Controller/EmployeeJobController.php
symfony/plugins/orangehrmPimPlugin/Service/EmployeeTerminationService.php
symfony/plugins/orangehrmPimPlugin/Service/Model/TerminationReasonModel.php
symfony/plugins/orangehrmPimPlugin/test/Api/EmployeeTerminationAPITest.php
symfony/plugins/orangehrmPimPlugin/test/Service/EmployeeTerminationServiceTest.php

Additional changes: Loader component added

OHRM5X-319: PIM - Employee Termination

---

symfony/client/src/core/util/validation/rules.ts
symfony/client/src/orangehrmPimPlugin/components/EditEmergencyContact.vue
symfony/client/src/orangehrmPimPlugin/components/SaveEmergencyContact.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeContactDetails.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeePersonalDetails.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/SaveEmployee.vue

OHRM5X-333:  Phone number field issue fixed
OHRM5X-257: fix the error shows when enter some of the accepted characters for one of the contact number fields
OHRM5X-244:  added Maximum allowed character field validation messages for Personal Details Screens
OHRM5X-230: Fix the validation rules for Contact Details except the unique email validation
OHRM5X-220: add * Required field text to add employee screen

OHRM5X-244: Character field validation messages for PIM Personal Details and Contact Details

---

symfony/client/src/core/components/inputs/PasswordInput.vue
symfony/client/src/core/util/validation/rules.ts
symfony/client/src/orangehrmAdminPlugin/pages/jobCategory/EditJobCategory.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobTitle/EditJobTitle.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobTitle/SaveJobTitle.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/EditSystemUser.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/SaveSystemUser.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/SaveEmployee.vue
symfony/plugins/orangehrmAdminPlugin/Controller/SaveJobTitleController.php
symfony/plugins/orangehrmCorePlugin/Service/ConfigService.php

OHRM5X-329: CSV file support added
OHRM5X-331: file uploader added to edit job title
OHRM5X-93: password field autocomplete off added
OHRM5X-87: Job category edit UI, loading state fix

OHRM5X-323: P1 Defect Fixes

---

symfony/client/src/orangehrmPimPlugin/pages/reportingMethod/ReportingMethod.vue
symfony/client/src/orangehrmPimPlugin/pages/terminationReason/TerminationReason.vue
symfony/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php
symfony/plugins/orangehrmPimPlugin/Api/ReportingMethodConfigurationAPI.php
symfony/plugins/orangehrmPimPlugin/Api/TerminationReasonConfigurationAPI.php
symfony/plugins/orangehrmPimPlugin/Controller/ReportingMethodController.php
symfony/plugins/orangehrmPimPlugin/Controller/TerminationReasonController.php
symfony/plugins/orangehrmPimPlugin/Dao/ReportingMethodConfigurationDao.php
symfony/plugins/orangehrmPimPlugin/Dao/TerminationReasonConfigurationDao.php
symfony/plugins/orangehrmPimPlugin/Service/ReportingMethodConfigurationService.php
symfony/plugins/orangehrmPimPlugin/Service/TerminationReasonConfigurationService.php
symfony/plugins/orangehrmPimPlugin/test/Dao/TerminationReasonConfigurationDaoTest.php

fix issue of the deletion issue of termination reasons and reporting methods.

OHRM5X-360: Block to delete already in use reporting methods and termination reasons

---

.github/ISSUE_TEMPLATE/bug_report.md
.gitignore
build/build.xml
fix_permissions.sh
installer/ApplicationSetupUtility.php

OHRM5X-348: Move installer log to symfony/log folder

---

symfony/client/package.json
symfony/client/src/core/components/inputs/EmployeeAutocomplete.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/EditSystemUser.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/SaveSystemUser.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/SystemUser.vue
symfony/client/src/orangehrmPimPlugin/components/EmploymentStatusDropdown.vue
symfony/client/src/orangehrmPimPlugin/components/JobtitleDropdown.vue
symfony/client/src/orangehrmPimPlugin/components/SubunitDropdown.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/Employee.vue
symfony/client/yarn.lock

- employee autocomplete added
- emp list filters updated to oxd-select
- user list filters updated to oxd-select

OHRM5X-357: employee search by middle name fix

---

symfony/client/src/components.ts
symfony/client/src/core/components/layout/Layout.vue
symfony/client/src/core/plugins/acl/acl.ts
symfony/client/src/main.ts
symfony/client/src/orangehrmPimPlugin/components/EditEmployeeLayout.vue
symfony/client/src/orangehrmPimPlugin/components/ProfileCustomFields.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeePersonalDetails.vue

OHRM5X-370: PIM - Custom field implementation
Other fixes:
OHRM5X-294: PIM - Admin user can change his own job details
OHRM5X-345: PIM - Admin should not be able to terminate his own employment.
OHRM5X-358: PIM block updating sensitve info

OHRM5X-370: PIM - Custom field implementation

---

installer/dbscript/dbscript-2.sql
symfony/client/package.json
symfony/client/src/core/util/helper/year-range.ts
symfony/client/src/orangehrmAdminPlugin/pages/nationality/Nationality.vue
symfony/client/src/orangehrmPimPlugin/components/EditImmigration.vue
symfony/client/src/orangehrmPimPlugin/components/SaveImmigration.vue
symfony/client/src/orangehrmPimPlugin/index.ts
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeImmigration.vue
symfony/client/src/orangehrmPimPlugin/pages/terminationReason/TerminationReason.vue
symfony/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php
symfony/plugins/orangehrmPimPlugin/Api/EmployeeImmigrationRecordAPI.php
symfony/plugins/orangehrmPimPlugin/Api/Model/EmployeeImmigrationModel.php
symfony/plugins/orangehrmPimPlugin/Controller/BaseViewEmployeeController.php
symfony/plugins/orangehrmPimPlugin/Controller/EmployeeImmigrationController.php
symfony/plugins/orangehrmPimPlugin/Dao/EmployeeImmigrationRecordDao.php
symfony/plugins/orangehrmPimPlugin/Dto/EmployeeImmigrationRecordSearchFilterParams.php
symfony/plugins/orangehrmPimPlugin/Service/EmployeeImmigrationRecordService.php
symfony/plugins/orangehrmPimPlugin/config/routes.yaml
symfony/plugins/orangehrmPimPlugin/entity/Decorator/EmployeeImmigrationRecordDecorator.php
symfony/plugins/orangehrmPimPlugin/entity/EmployeeImmigrationRecord.php
symfony/plugins/orangehrmPimPlugin/test/Api/EmployeeImmigrationRecordAPITest.php
symfony/plugins/orangehrmPimPlugin/test/Dao/EmployeeImmigrationRecordDaoTest.php
symfony/plugins/orangehrmPimPlugin/test/Entity/EmployeeImmigrationRecordTest.php
symfony/plugins/orangehrmPimPlugin/test/Service/EmployeeImmigrationServiceTest.php
symfony/plugins/orangehrmPimPlugin/test/fixtures/EmployeeImmigrationRecordDao.yml

fixed OHRM5X-398: [Nationalities] Issues regarding card title font 
fixed OHRM5X-360:  Error toast message .

OHRM5X-207:PIM - Immigration

---

installer/dbscript/dbscript-2.sql
symfony/client/package.json
symfony/client/src/components.ts
symfony/client/src/core/components/inputs/DateInput.vue
symfony/client/src/core/util/helper/datefns.ts
symfony/client/src/orangehrmPimPlugin/components/EditDependent.vue
symfony/client/src/orangehrmPimPlugin/components/EditEducation.vue
symfony/client/src/orangehrmPimPlugin/components/EditImmigration.vue
symfony/client/src/orangehrmPimPlugin/components/EditLicense.vue
symfony/client/src/orangehrmPimPlugin/components/EditWorkExperience.vue
symfony/client/src/orangehrmPimPlugin/components/SaveDependent.vue
symfony/client/src/orangehrmPimPlugin/components/SaveEducation.vue
symfony/client/src/orangehrmPimPlugin/components/SaveImmigration.vue
symfony/client/src/orangehrmPimPlugin/components/SaveLicense.vue
symfony/client/src/orangehrmPimPlugin/components/SaveWorkExperience.vue
symfony/client/src/orangehrmPimPlugin/components/TerminateModal.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeePersonalDetails.vue
symfony/client/yarn.lock

- OHRM5X-432: Work week & holiday added to date input
- OHRM5X-432: Replace oxd-date input field

OHRM5X-432:work week & holiday added to date input

---

symfony/client/messages.en_US.json
symfony/client/src/components.ts
symfony/client/src/core/components/inputs/TimeInput.vue
symfony/client/src/core/util/helper/datefns.ts
symfony/client/src/core/util/validation/__tests__/rules.spec.ts
symfony/client/src/core/util/validation/rules.ts
symfony/client/src/orangehrmLeavePlugin/components/LeaveBalance.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveBalanceModal.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveConflict.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveDurationInput.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveTypeDropdown.vue
symfony/client/src/orangehrmLeavePlugin/index.ts
symfony/client/src/orangehrmLeavePlugin/pages/LeaveApply.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveAssign.vue
symfony/client/src/orangehrmLeavePlugin/pages/leave/LeaveApply.vue
symfony/plugins/orangehrmLeavePlugin/Controller/ApplyLeaveController.php
symfony/plugins/orangehrmLeavePlugin/Controller/AssignLeaveController.php
symfony/plugins/orangehrmLeavePlugin/config/routes.yaml

- OHRM5X-400: Leave - Develop Apply Leave UI
- OHRM5X-412: Leave - Develop Assign Leave UI

OHRM5X-400: Leave - Apply Leave, Assign Leave Screens

---

symfony/client/package.json
symfony/client/src/core/components/inputs/TimeInput.vue
symfony/client/src/core/util/validation/rules.ts
symfony/client/src/orangehrmLeavePlugin/components/LeaveDurationInput.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveApply.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveAssign.vue
symfony/client/src/orangehrmLeavePlugin/pages/configure/LeavePeriod.vue
symfony/client/yarn.lock

- package json updated
- OHRM5X-478: time input changed to 24h
- OHRM5X-400: leave balance disabled

OHRM5X-478: time input changed to 24h

---

symfony/client/src/orangehrmLeavePlugin/pages/configure/LeavePeriod.vue

- OHRM5X-407: Leave - Current leave period added
- OHRM5X-407: Leave - leave period not loading fix

OHRM5X-407: Leave - Current leave period added

---

symfony/client/messages.en_US.json
symfony/client/src/orangehrmAdminPlugin/pages/organizationGeneralInformation/ViewOrganizationGeneralInformation.vue
symfony/client/src/orangehrmLeavePlugin/index.ts
symfony/client/src/orangehrmLeavePlugin/pages/configure/WorkWeek.vue
symfony/client/src/orangehrmPimPlugin/components/EditLanguage.vue
symfony/client/src/orangehrmPimPlugin/components/EditSalaryComponent.vue
symfony/client/src/orangehrmPimPlugin/components/SaveSalaryComponent.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeContactDetails.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeePersonalDetails.vue
symfony/plugins/orangehrmLeavePlugin/Controller/WorkWeekController.php
symfony/plugins/orangehrmLeavePlugin/config/routes.yaml

Need to change the drop-downs of Qualification screens and save salary screen (edit is working, but save doesn't work)

OHRM5X-409: Configure - Work Week

---

symfony/client/src/orangehrmPimPlugin/components/EditLanguage.vue
symfony/client/src/orangehrmPimPlugin/components/QualificationDropdown.vue
symfony/client/src/orangehrmPimPlugin/components/SaveEducation.vue
symfony/client/src/orangehrmPimPlugin/components/SaveLanguage.vue
symfony/client/src/orangehrmPimPlugin/components/SaveLicense.vue
symfony/client/src/orangehrmPimPlugin/components/SaveSalaryComponent.vue

didn't fix the save salary component

OHRM5X-437: Drop down and autocomplete fields in Admin and PIM screens

---

symfony/client/src/core/components/inputs/DateInput.vue
symfony/client/src/orangehrmLeavePlugin/pages/configure/LeavePeriod.vue
symfony/client/src/orangehrmPimPlugin/components/EditEmployeeReportTo.vue
symfony/client/src/orangehrmPimPlugin/components/SaveEmployeeReportTo.vue
symfony/client/src/orangehrmPimPlugin/components/SaveSkill.vue

- OHRM5X-540: date picker full day holiday color fix
- OHRM5X-518: leave period, reset button added
- OHRM5X-509: current leave period not updating fix
- OHRM5X-517:Report-to reporting method dropdown fix
- OHRM5X-513: skill dropdown not selecting fix

OHRM5X-320: P2 Defect fixes

---

symfony/apps/orangehrm/templates/vue.html.twig
symfony/client/messages.en_US.json
symfony/client/package.json
symfony/client/src/orangehrmLeavePlugin/components/LeaveComment.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveCommentsModal.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveListTable.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveListTableHeader.vue
symfony/client/src/orangehrmLeavePlugin/index.ts
symfony/client/src/orangehrmLeavePlugin/pages/LeaveList.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveRequest.vue
symfony/client/yarn.lock
symfony/plugins/orangehrmAdminPlugin/Service/Model/SubunitModel.php
symfony/plugins/orangehrmLeavePlugin/Controller/LeaveListController.php
symfony/plugins/orangehrmLeavePlugin/Controller/LeaveRequestController.php
symfony/plugins/orangehrmLeavePlugin/Controller/SaveLeaveEntitlementController.php
symfony/plugins/orangehrmLeavePlugin/config/routes.yaml

OHRM5X-411: Leave - Develop Leave List UI
OHRM5X-411: Leave - Develop Leave Request List UI

OHRM5X-411: Leave - Develop Leave List UI

---

installer/dbscript/dbscript-2.sql
symfony/client/src/orangehrmAdminPlugin/pages/moduleConfiguration/EditModuleConfiguration.vue
symfony/client/src/pages.ts
symfony/plugins/orangehrmAdminPlugin/Api/ModulesAPI.php
symfony/plugins/orangehrmAdminPlugin/Controller/SaveModuleConfigurationController.php
symfony/plugins/orangehrmAdminPlugin/config/routes.yaml
symfony/plugins/orangehrmAdminPlugin/test/Api/ModulesAPITest.php
symfony/plugins/orangehrmAdminPlugin/test/Dao/ModuleDaoTest.php
symfony/plugins/orangehrmAdminPlugin/test/Service/ModuleServiceTest.php
symfony/plugins/orangehrmAdminPlugin/test/fixtures/ModuleDao.yml
symfony/plugins/orangehrmAdminPlugin/test/fixtures/testcases/ModulesAPI.yml
symfony/plugins/orangehrmCoreOAuthPlugin/Dao/OAuthClientDao.php
symfony/plugins/orangehrmCoreOAuthPlugin/Service/OAuthService.php
symfony/plugins/orangehrmCoreOAuthPlugin/test/Dao/OAuthClientDaoTest.php
symfony/plugins/orangehrmCoreOAuthPlugin/test/Service/OAuthServiceTest.php
symfony/plugins/orangehrmCorePlugin/Dao/ModuleDao.php
symfony/plugins/orangehrmCorePlugin/Service/ModuleService.php

This is a partial merge request just to verify whether the followed approach is correct. Please have a look and give me feedback. Following are the pending items.
1. The menu item should be added for the Admin
2. Should implement unit tests for DAO, Services and APIs
3. Should implement Cypress tests
4. Should write the API documentation
5. Code formatting and Eslint

OHRM5X-276 : Add Configure Modules screen in Admin module

---

symfony/client/messages.en_US.json
symfony/client/src/core/components/inputs/EmployeeAutocomplete.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveBalance.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveBalanceInsufficientModal.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveBalanceModal.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveConflict.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveDurationInput.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveEntitlementTable.vue
symfony/client/src/orangehrmLeavePlugin/components/LeaveListTable.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveApply.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveAssign.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveList.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveRequest.vue
symfony/client/src/orangehrmLeavePlugin/pages/MyLeaveList.vue
symfony/client/src/orangehrmLeavePlugin/pages/configure/WorkWeek.vue
symfony/client/src/orangehrmLeavePlugin/pages/configure/holiday/Holiday.vue
symfony/client/src/orangehrmLeavePlugin/pages/entitlements/AddEntitlement.vue
symfony/client/src/orangehrmPimPlugin/components/ReportToEmployeeAutocomplete.vue
symfony/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveEntitlementAPI.php
symfony/plugins/orangehrmLeavePlugin/Api/LeaveEntitlementAPI.php
symfony/plugins/orangehrmLeavePlugin/Controller/LeaveRequestController.php
symfony/plugins/orangehrmLeavePlugin/Controller/WorkWeekController.php

- OHRM5X-612: Set Apply leave duration default value
- OHRM5X-632: Set Apply leave to date when selecting from date
- OHRM5X-645: Leave conflict modal typo fixes
- OHRM5X-636: Apply leave balance insufficent text color changed
- OHRM5X-654: Fix Apply leave duration conversion to decimal hours
- OHRM5X-633: Fix Leave conflict toast message
- OHRM5X-658: Add days suffix to Leave balance modal, balance
- OHRM5X-630: Add no leave types available message to apply leave

OHRM5X-678: Fix leave screen issues

---

symfony/test/functional/cypress/fixtures/charLength.json
symfony/test/functional/cypress/integration/orangehrm/admin/organization-structure.spec.js
symfony/test/functional/cypress/integration/orangehrm/admin/paygrade.spec.js
symfony/test/functional/cypress/integration/orangehrm/admin/structure.spec.js
symfony/test/functional/cypress/integration/orangehrm/pim/config-customfields.spec.js

Test Automation: Admin-Pay Grades

OHRM5X-676 & OHRM5X-487: Test Automation: Admin-Pay Grades & Organization Structure

---

symfony/client/src/orangehrmPimPlugin/pages/updatePassword/UpdatePassword.vue

This PR Contains Following fixes:
1. Navigation back issue after successfully updated the password.
2. Navigation back issue after user clicking cancel button.
3. one scss link removed from Vue component.

OHRM5X-898: Password update related bugs fixes added

---

installer/dbscript/dbscript-2.sql
symfony/apps/orangehrm/templates/vue.html.twig
symfony/plugins/orangehrmCorePlugin/Dao/MenuDao.php
symfony/plugins/orangehrmCorePlugin/Helper/VueControllerHelper.php
symfony/plugins/orangehrmCorePlugin/Subscriber/ModuleUnderDevelopmentSubscriber.php
symfony/plugins/orangehrmCorePlugin/test/Dao/MenuDaoTest.php

1. Module enhancement added for index pages.
2. Module under development missed URLs added.
3. Dao test added for newly added methods.

OHRM5X-851: Menu enhancement added for index pages

---

symfony/client/package.json
symfony/client/src/core/util/composable/useForm.ts
symfony/client/src/orangehrmAdminPlugin/pages/orgStructure/org-structure.scss
symfony/client/src/orangehrmLeavePlugin/pages/LeaveApply.vue
symfony/client/src/orangehrmLeavePlugin/pages/LeaveAssign.vue
symfony/client/src/orangehrmLeavePlugin/pages/entitlements/AddEntitlement.vue
symfony/client/src/orangehrmPimPlugin/components/ReportCriterionDateRange.vue
symfony/client/src/orangehrmPimPlugin/pages/dataImport/EmployeeDataImport.vue
symfony/client/src/orangehrmPimPlugin/pages/reports/EditEmployeeReport.vue
symfony/client/src/orangehrmPimPlugin/pages/reports/SaveEmployeeReport.vue
symfony/client/src/orangehrmPimPlugin/pages/reports/employee-report.scss
symfony/client/src/orangehrmPimPlugin/util/composable/useEmployeeReport.ts
symfony/client/yarn.lock
symfony/plugins/orangehrmLeavePlugin/Controller/SaveLeaveEntitlementController.php
symfony/plugins/orangehrmLeavePlugin/Controller/ViewLeaveEntitlementController.php
symfony/plugins/orangehrmLeavePlugin/Controller/ViewMyLeaveEntitlementController.php

- OHRM5X-609: Leave Entitlement pre-populate current leave period
- OHRM5X-884: Add/Edit PIM report back button renamed
- OHRM5X-880: PIM Report joined date criterion operator labels changed
- OHRM5X-858: Add PIM reports display fields warning toast
- OHRM5X-575: Form reset validation issues fixed

OHRM5X-904: PIM Reports defect fixes

---

symfony/client/src/core/util/validation/rules.ts
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/AddPayGrade.vue
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/EditPayCurrency.vue
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/EditPayGrade.vue
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/PayGradeCurrency.vue
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/SavePayCurrency.vue
symfony/test/functional/cypress/integration/orangehrm/admin/paygrade.spec.js

This PR Contains following fixes:
1. OHRM5X-582: When adding a new pay grade "Successfully Added" toast message display instead of "Successfully Saved"
2. OHRM5X-576: Min/Max salary fields validation message amount should be comma separated.
3. OHRM5X-579 UI:
1. Add currency button is a tool button.
2. Edit currency form title is " Add Currency"
3. Add currency form currency field is not according to the ui.

OHRM5X-753: Paygrade bug fixes added

---

symfony/client/src/orangehrmAdminPlugin/pages/emailSubscription/EmailSubscription.vue
symfony/client/src/orangehrmAdminPlugin/pages/orgStructure/EditOrgUnit.vue
symfony/client/src/orangehrmAdminPlugin/pages/orgStructure/SaveOrgUnit.vue
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/AddPayGrade.vue
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/EditPayGrade.vue
symfony/client/src/orangehrmPimPlugin/components/EditDependent.vue
symfony/client/src/orangehrmPimPlugin/components/SaveDependent.vue
symfony/client/src/orangehrmPimPlugin/components/SaveSalaryComponent.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/Employee.vue

- OHRM5X-232: PIM Redirect to employee profile on click employee list
- OHRM5X-516: PIM Salary, Dependants remove default values
- OHRM5X-854: Limit subscribers shown in Email Subscription list
- OHRM5X-954: Org unit name unique validation is case sensitive fix

OHRM5X-324: P3 Defect Fixes

---

CHANGELOG.TXT

1. Change log added for OHRM-OS 5.0-beta.

OHRM5X-555 : Updated OHRM-OS 5.0-beta change log

---

symfony/client/src/orangehrmTimePlugin/index.ts
symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
symfony/client/src/orangehrmTimePlugin/pages/project/ProjectEdit.vue
symfony/plugins/orangehrmTimePlugin/Api/ValidateProjectNameAPI.php

This PR contains - 
- Project Edit screen
- Removed hard coded labels and added translations
Known Issues -
- Need to add styling for ProjectAdminAutocomplete component

OHRM5X-553: Develop time - edit project  screen

---

symfony/plugins/orangehrmTimePlugin/Api/TimeConfigPeriodAPI.php
symfony/plugins/orangehrmTimePlugin/Service/TimesheetPeriodService.php
symfony/plugins/orangehrmTimePlugin/Service/TimesheetService.php

1. Case sensitive issue fixed in TimeSheetPeriodService file(Changed to TimesheetPeriodService).

OHRM5X-988: Fix TimesheetPeriodService case sensitive issue

---

symfony/plugins/orangehrmTimePlugin/Api/ValidationRules/MyTimesheetDateRule.php
symfony/plugins/orangehrmTimePlugin/Controller/MyTimesheetController.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/Service/TimesheetService.php
symfony/plugins/orangehrmTimePlugin/test/Dao/TimesheetDaoTest.php

This PR Contains following Changes:
1. OHRM5X-986: Create default Timesheet By System Its Self Feature Added.
2. Inside the MyTimesheetController Transaction method added for evaluating the default Timesheet creation.

OHRM5X-986: Create default Timesheet By System Its Self Feature Added

---

installer/dbscript/dbscript-2.sql
symfony/plugins/orangehrmTimePlugin/Api/MyTimesheetAPI.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/Dto/MyTimesheetSearchFilterParams.php
symfony/plugins/orangehrmTimePlugin/Service/TimesheetService.php
symfony/plugins/orangehrmTimePlugin/config/routes.yaml
symfony/plugins/orangehrmTimePlugin/test/Api/TimesheetAPITest.php
symfony/plugins/orangehrmTimePlugin/test/Dao/TimesheetDaoTest.php
symfony/plugins/orangehrmTimePlugin/test/fixtures/MyTimesheetAPITest.yml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/TimesheetTestCase.yaml

This PR includes:-
- End point for getAll timesheets
- Intergrated testing for API

OHRM5X-998 - MyTimesheet getAll

---

installer/dbscript/dbscript-2.sql
symfony/plugins/orangehrmTimePlugin/Api/EmployeeTimesheetItemAPI.php
symfony/plugins/orangehrmTimePlugin/Api/MyTimesheetAPI.php
symfony/plugins/orangehrmTimePlugin/Api/Traits/TimesheetPermissionTrait.php
symfony/plugins/orangehrmTimePlugin/Api/ValidationRules/MyTimesheetActionRule.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/Service/TimesheetService.php
symfony/plugins/orangehrmTimePlugin/config/routes.yaml
symfony/plugins/orangehrmTimePlugin/entity/Decorator/TimesheetActionLogDecorator.php
symfony/plugins/orangehrmTimePlugin/entity/Timesheet.php
symfony/plugins/orangehrmTimePlugin/test/Api/TimesheetAPITest.php
symfony/plugins/orangehrmTimePlugin/test/Dao/TimesheetDaoTest.php
symfony/plugins/orangehrmTimePlugin/test/fixtures/MyTimesheetAPITest.yml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/TimesheetTestCase.yaml

1. OHRM5X-994: MyTimesheetAPI Update API added.
2. API Integration test added for the API.
3. Data group permission added for the API.

OHRM5X-994: MyTimesheet Allowed Action (update) feature added

---

installer/dbscript/dbscript-2.sql
symfony/plugins/orangehrmTimePlugin/Api/Model/TimesheetItemModel.php
symfony/plugins/orangehrmTimePlugin/Api/MyTimesheetAPI.php
symfony/plugins/orangehrmTimePlugin/Api/TimesheetCommentAPI.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/config/routes.yaml
symfony/plugins/orangehrmTimePlugin/entity/Decorator/TimesheetItemDecorator.php
symfony/plugins/orangehrmTimePlugin/test/Api/TimesheetCommentAPITest.php
symfony/plugins/orangehrmTimePlugin/test/Dao/TimesheetDaoTest.php
symfony/plugins/orangehrmTimePlugin/test/fixtures/TimesheetComment.yaml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/TimesheetCommentTestCase.yaml

1. OHRM5X-997: Timesheet comment API added (Create, GET One and Update)
2. Unit tests added for DAO and API Layers
3. Data group permission added.

OHRM5X-997: Timesheet comment API added

---

installer/dbscript/dbscript-2.sql
symfony/plugins/orangehrmTimePlugin/Api/MyTimesheetAPI.php
symfony/plugins/orangehrmTimePlugin/Api/TimesheetProjectActivityUniqueValidationAPI.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/Dto/TimesheetSearchFilterParams.php
symfony/plugins/orangehrmTimePlugin/config/routes.yaml
symfony/plugins/orangehrmTimePlugin/test/Api/TimesheetProjectActivityUniqueValidationAPITest.php
symfony/plugins/orangehrmTimePlugin/test/Dao/TimesheetDaoTest.php
symfony/plugins/orangehrmTimePlugin/test/fixtures/TimesheetProjectActivityAPITest.yml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/TimesheetProjectActivityUniqueValidationTestCase.yaml

This PR includes:
Back-end API for duplicate project activity validation
Integrated testing for API
Unit test for DAO

OHRM5X-990 - Duplicate project activity validation

---

installer/dbscript/dbscript-2.sql
symfony/plugins/orangehrmTimePlugin/Api/DefaultTimesheetAPI.php
symfony/plugins/orangehrmTimePlugin/Api/EmployeeTimesheetAPI.php
symfony/plugins/orangehrmTimePlugin/Api/Model/DefaultTimesheetModel.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/Dto/DefaultTimesheetSearchFilterParams.php
symfony/plugins/orangehrmTimePlugin/Dto/TimesheetSearchFilterParams.php
symfony/plugins/orangehrmTimePlugin/config/routes.yaml
symfony/plugins/orangehrmTimePlugin/test/Api/DefaultTimesheetAPITest.php
symfony/plugins/orangehrmTimePlugin/test/Dao/TimesheetDaoTest.php
symfony/plugins/orangehrmTimePlugin/test/fixtures/DefaultTimesheetTest.yml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/DefaultTimesheetAPITestCase.yaml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/EmployeeTimesheetAPITestCases.yaml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/TimesheetTestCase.yaml

This PR contains:
New API (DefaultTimesheetAPI) for getting default time sheets
Units tests
Intergration tests for API
Modifications for default behaviour of EmployeeTimesheetAPI

OHRM5X-987: Default Timesheets

---

symfony/plugins/orangehrmTimePlugin/Api/TimeReportAPI.php
symfony/plugins/orangehrmTimePlugin/Api/TimeReportDataAPI.php
symfony/plugins/orangehrmTimePlugin/Report/EmployeeReport.php
symfony/plugins/orangehrmTimePlugin/Report/ProjectReport.php
symfony/plugins/orangehrmTimePlugin/config/routes.yaml

1. OHRM5X-1006: Folder Structure initiated

OHRM5X-1006: Initiated time - report APIs

---

symfony/plugins/orangehrmTimePlugin/Controller/EditTimesheetController.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/Dto/EmployeeTimesheetListSearchFilterParams.php

This PR Contains following fixes:
1. OHRM5X-1067 - [Time - Employee timesheets] Default pending action list is arranged based on the alphabetical order of Employee Lastname
2. OHRM5X-1071 - [Time - Employee timesheets] In edit timesheet, when timesheet id parameter is changed to a non existing work shift number in URL a 500 error is getting displayed.

OHRM5X-1067: Time sheet related bug fixes added

---

symfony/lib/orm/Doctrine.php
symfony/lib/orm/TimeDiff.php
symfony/plugins/orangehrmAttendancePlugin/Dao/AttendanceDao.php
symfony/plugins/orangehrmAttendancePlugin/entity/AttendanceRecord.php
symfony/plugins/orangehrmAttendancePlugin/test/Dao/AttendanceDaoTest.php
symfony/plugins/orangehrmPimPlugin/entity/Employee.php
symfony/plugins/orangehrmTimePlugin/Api/TimeReportAPI.php
symfony/plugins/orangehrmTimePlugin/Api/TimesheetCommentAPI.php
symfony/plugins/orangehrmTimePlugin/Dto/AttendanceReportSearchFilterParams.php
symfony/plugins/orangehrmTimePlugin/Report/AttendanceReport.php
symfony/plugins/orangehrmTimePlugin/Report/AttendanceReportData.php
symfony/plugins/orangehrmTimePlugin/test/Api/AttendanceReportAPITest.php
symfony/plugins/orangehrmTimePlugin/test/Api/AttendanceReportDataAPITest.php
symfony/plugins/orangehrmTimePlugin/test/fixtures/AttendanceReportDataAPITest.yaml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/AttendanceReportAPITestCase.yaml
symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/AttendanceReportDataAPITestCase.yaml

This PR Contains following changes and fixes:
1. Attendance Report End point added for Table Structure and Data.
2. Data group and Role permission added.
3. Unit tests and integration test added.
4. OHRM5X-1072 - [Time - Employee timesheets] Timesheet comment fields should not be a required field] issue fixed.

OHRM5X-559: Attendance report end point added

---

symfony/plugins/orangehrmAttendancePlugin/Api/EmployeeAttendanceRecordAPI.php
symfony/plugins/orangehrmAttendancePlugin/Dao/AttendanceDao.php
symfony/plugins/orangehrmAttendancePlugin/Exception/AttendanceServiceException.php
symfony/plugins/orangehrmAttendancePlugin/test/fixtures/testcases/EmployeeAttendanceRecordAPITestCases.yaml
symfony/plugins/orangehrmAttendancePlugin/test/fixtures/testcases/MyAttendanceRecordAPITestCases.yaml

Refactored Employee Attendance Record API delete endpoint
Improved Test coverage for delete endpoint

OHRM5X-1093: Employee Attendance Record API Delete Endpoint

---

symfony/client/src/orangehrmTimePlugin/components/ProjectAdminAutocomplete.vue
symfony/client/src/orangehrmTimePlugin/pages/project/ProjectEdit.vue
symfony/client/src/orangehrmTimePlugin/pages/project/ProjectSave.vue
symfony/client/src/orangehrmTimePlugin/pages/reports/EmployeeTimeReport.vue
symfony/plugins/orangehrmTimePlugin/Api/ProjectAPI.php
symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
symfony/plugins/orangehrmTimePlugin/Dto/EmployeeReportsSearchFilterParams.php

- Bug fixes For OHRM5X-1136
- Bug fixes For OHRM5X-1118
- Bug fixes For OHRM5X-1114
- Bug fixes For OHRM5X-1110

OHRM5X-1110: Fix time - project/ employee report screen issues

---

installer/ApplicationSetupUtility.php
installer/upgrader/Migrations/V5/AttendanceHelper.php
installer/upgrader/Migrations/Version20220301.php
installer/upgrader/console.php

1. OHRM5X-1160: Attendance Upgrader added.
2. Migration file and related Doctrine Database Abstraction Layer added.

OHRM5X-1160: Attendance Upgrader added

---

symfony/client/src/orangehrmAttendancePlugin/components/RecordAttendance.vue
symfony/client/src/orangehrmAttendancePlugin/components/TimezoneDropdown.vue
symfony/client/src/orangehrmAttendancePlugin/pages/EditAttendance.vue
symfony/plugins/orangehrmAttendancePlugin/Api/AttendanceRecordAPI.php
symfony/plugins/orangehrmAttendancePlugin/Controller/ViewEmployeeAttendanceController.php
symfony/plugins/orangehrmAttendancePlugin/Exception/AttendanceServiceException.php
symfony/plugins/orangehrmAttendancePlugin/test/fixtures/testcases/AttendanceRecordAPITestCases.yaml

Timezone Dropdown connected with the API
Bug fix OHRM5X-1157
Bug fix OHRM5X-1158
Bug fix OHRM5X-1165
Bug fix OHRM5X-1138
Bug fix OHRM5X-1168
Bug fix OHRM5X-1169
Bug fix OHRM5X-1166
Bug fix OHRM5X-1176
Bug fix OHRM5X-1171

OHRM5X-1177: Timezone Dropdown And Attendance Related Bug Fixes

---

installer/upgrader/Migrations/V5/adminLangString.yaml
installer/upgrader/Migrations/V5/generalLangString.yaml
symfony/client/src/core/components/inputs/EmployeeAutocomplete.vue
symfony/client/src/core/components/inputs/PasswordInput.vue
symfony/client/src/core/components/layout/Layout.vue
symfony/client/src/core/components/table/TableHeader.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobTitle/EditJobTitle.vue
symfony/client/src/orangehrmAdminPlugin/pages/jobTitle/SaveJobTitle.vue
symfony/client/src/orangehrmAdminPlugin/pages/localization/LocalizationConfiguration.vue
symfony/client/src/orangehrmAdminPlugin/pages/location/SaveLocation.vue
symfony/client/src/orangehrmAdminPlugin/pages/orgStructure/EditOrgUnit.vue
symfony/client/src/orangehrmAdminPlugin/pages/orgStructure/SaveOrgUnit.vue
symfony/client/src/orangehrmAdminPlugin/pages/payGrade/PayGradeCurrency.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationLicense/License.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationSkill/EditQualificationSkill.vue
symfony/client/src/orangehrmAdminPlugin/pages/qualificationSkill/SaveQualificationSkill.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/EditSystemUser.vue
symfony/client/src/orangehrmAdminPlugin/pages/systemUser/SystemUser.vue
symfony/client/src/orangehrmAdminPlugin/pages/workShift/SaveWorkShift.vue

fixed the ones except for the topbar

OHRM5X-1151: Fix issues pointed out by QA

---

installer/upgrader/Migrations/V5/generalLangString.yaml
installer/upgrader/Migrations/V5/maintenanceLangString.yaml
installer/upgrader/Migrations/Version20220221.php
installer/upgrader/runTranslationTest.php
installer/upgrader/runTranslations.php
symfony/client/src/orangehrmAuthenticationPlugin/pages/AdministratorAccess.vue
symfony/client/src/orangehrmMaintenancePlugin/components/EmployeeRecords.vue
symfony/client/src/orangehrmMaintenancePlugin/components/MaintenanceNote.vue
symfony/client/src/orangehrmMaintenancePlugin/components/SelectedEmployee.vue
symfony/client/src/orangehrmMaintenancePlugin/pages/PurgeEmployee.vue
symfony/plugins/orangehrmAuthenticationPlugin/Controller/AdministratorAccessController.php
symfony/plugins/orangehrmAuthenticationPlugin/Controller/Traits/AdministratorAccessTrait.php

PR contains:
- Lang strings for Purge Employee  Screen
- Lang strings for  Administrator Access Screen
- Styling changes requested in [admin access PR](https://github.com/orangehrm/orangehrm/pull/1171)

OHRM5X-1213: Purge Employee and Admin Access Lang Strings

---

symfony/client/src/orangehrmAuthenticationPlugin/pages/AdministratorAccess.vue
symfony/lib/config/Config.php
symfony/plugins/orangehrmAdminPlugin/Api/JobTitleAPI.php
symfony/plugins/orangehrmAuthenticationPlugin/Controller/ValidateController.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules/Base64Attachment.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules/EntityUniqueProperty.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules/EntityUniquePropertyOption.php
symfony/plugins/orangehrmCorePlugin/Subscriber/SessionSubscriber.php
symfony/plugins/orangehrmCorePlugin/config/CorePluginConfiguration.php
symfony/test/functional/cypress/support/commands.js

PR contains:
- OHRM5X-666: OS Internal Security Assessment - Session handling, validation of session
- OHRM5X-664 reopen fix
- OHRM5X-1232 [Job Title][Broken] Invalid parameter error message is getting displayed when user replace or add a new job specification in edit screen.

OHRM5X-666: Session Login/Logout Handling

---

symfony/client/src/orangehrmAttendancePlugin/pages/EditAttendance.vue
symfony/plugins/orangehrmAttendancePlugin/Api/AttendanceRecordAPI.php
symfony/plugins/orangehrmAttendancePlugin/test/fixtures/testcases/AttendanceRecordAPITestCases.yaml

OHRM5X-1181 two column issue fix
OHRM5X-1244 Broken issue fix

OHRM5X-1181:Two Column Issue Fixed

---

symfony/client/src/core/util/validation/__tests__/rules.spec.ts
symfony/client/src/core/util/validation/rules.ts
symfony/client/src/orangehrmAdminPlugin/pages/location/EditLocation.vue
symfony/client/src/orangehrmAdminPlugin/pages/location/SaveLocation.vue
symfony/client/src/orangehrmAdminPlugin/pages/organizationGeneralInformation/ViewOrganizationGeneralInformation.vue
symfony/client/src/orangehrmPimPlugin/components/EditEmergencyContact.vue
symfony/client/src/orangehrmPimPlugin/components/SaveEmergencyContact.vue
symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeContactDetails.vue
symfony/client/src/orangehrmTimePlugin/components/TimesheetActions.vue
symfony/plugins/orangehrmAdminPlugin/Api/EmailConfigurationAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/EmailSubscriberAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/LocationAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/OrganizationAPI.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules/Email.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules/Phone.php
symfony/plugins/orangehrmCorePlugin/Import/PimCsvDataImport.php
symfony/plugins/orangehrmPimPlugin/Api/EmpEmergencyContactAPI.php
symfony/plugins/orangehrmPimPlugin/Api/EmployeeContactDetailsAPI.php
symfony/plugins/orangehrmPimPlugin/Api/ValidationEmployeeEmailAPI.php

PR contains:
- OHRM5X-1243: OS Internal Security Assessment - Input validation is not properly handled from the back-end for user inputs

OHRM5X-1243: Improve Input Validation for Backend

---

installer/Migration/V5_0_0/lang-string/general.yaml
symfony/client/package.json
symfony/client/src/core/components/inputs/FileUploadInput.vue
symfony/client/src/orangehrmPimPlugin/components/EditAttachment.vue
symfony/client/src/orangehrmPimPlugin/components/SaveAttachment.vue
symfony/client/src/orangehrmPimPlugin/pages/dataImport/EmployeeDataImport.vue
symfony/client/yarn.lock

Keeping draft until https://github.com/orangehrm/oxd/pull/262 is merged

OHRM5X-1233: Missing i18n messages added

---

symfony/plugins/orangehrmAdminPlugin/Api/EmailSubscriberAPI.php
symfony/plugins/orangehrmAdminPlugin/Api/UserAPI.php
symfony/plugins/orangehrmAdminPlugin/Dao/EmailSubscriberDao.php
symfony/plugins/orangehrmAdminPlugin/test/Dao/EmailSubscriberDaoTest.php
symfony/plugins/orangehrmAdminPlugin/test/fixtures/EmailSubscriptionDao.yaml
symfony/plugins/orangehrmAdminPlugin/test/fixtures/testcases/EmailSubscriberTestCase.yaml
symfony/plugins/orangehrmAdminPlugin/test/fixtures/testcases/EmailSubscriptionTestCase.yaml
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules/Base64Attachment.php
symfony/plugins/orangehrmCorePlugin/Exception/CSVUploadFailedException.php
symfony/plugins/orangehrmCorePlugin/Service/CsvDataImportService.php
symfony/plugins/orangehrmCorePlugin/test/Import/CsvDataImportServiceTest.php
symfony/plugins/orangehrmPimPlugin/Api/EmpEmergencyContactAPI.php
symfony/plugins/orangehrmPimPlugin/Api/EmployeeCSVImportAPI.php
symfony/plugins/orangehrmPimPlugin/Api/EmployeeContactDetailsAPI.php

PR contains:
- OHRM5X-1235: OS Internal Security Assessment - [API] 500 internal server error is thrown for payload when pass via API
- OHRM5X-1238: OS Internal Security Assessment - Failure to validate the user-supplied content - PIM Data Import
- OHRM-664: Identified issues
- Can not attach files (when extension is in capitals).
- OHRM-1243: Identified issues
- Can add already existing email addresses for subscribers in Email Subscription screen.
- Numbers containing more than 25 characters can be added via the API.

OHRM5X-1235: Improve Internal Server Error Handling

---

symfony/client/src/core/util/helper/password.ts
symfony/client/src/orangehrmAdminPlugin/pages/location/EditLocation.vue
symfony/client/src/orangehrmAdminPlugin/pages/location/SaveLocation.vue
symfony/client/src/orangehrmPimPlugin/pages/reports/SaveEmployeeReport.vue
symfony/plugins/orangehrmAdminPlugin/Api/UserAPI.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules.php
symfony/plugins/orangehrmCorePlugin/Api/V2/Validator/Rules/Password.php
symfony/plugins/orangehrmPimPlugin/Api/UpdatePasswordAPI.php
symfony/plugins/orangehrmPimPlugin/test/fixtures/testcases/UpdatePasswordTestCase.yaml

PR contains:
- OHRM5X-668: OS Internal Security Assessment - Password policy configuration should be implemented in backend

OHRM5X-668: Improve Password Validation in Backend

---

installer/Controller/Upgrader/Api/DatabaseConfigAPI.php
installer/Controller/Upgrader/Api/SystemCheckAPI.php
installer/Util/Messages.php
installer/Util/SystemConfig.php
installer/Util/UpgraderConfigUtility.php

This PR contains modifications regarding the review feedback of following PR
https://github.com/orangehrm/orangehrm/pull/1227

OHRM5X-1245: System Check Modifications

---

installer/Migration/V5_0_0/permission/api.yaml
src/client/src/orangehrmPimPlugin/pages/employee/EmployeeContactDetails.vue
src/plugins/orangehrmAdminPlugin/Api/ValidationUserNameAPI.php
src/plugins/orangehrmMaintenancePlugin/test/fixtures/EmployeeDao.yml
src/plugins/orangehrmPimPlugin/Api/EmployeeContactDetailsAPI.php
src/plugins/orangehrmPimPlugin/Api/ValidationEmployeeEmailAPI.php
src/plugins/orangehrmPimPlugin/Api/ValidationEmployeeOtherEmailAPI.php
src/plugins/orangehrmPimPlugin/Dao/EmployeeDao.php
src/plugins/orangehrmPimPlugin/config/routes.yaml
src/plugins/orangehrmPimPlugin/test/Api/EmployeeContactDetailsAPITest.php
src/plugins/orangehrmPimPlugin/test/Api/ValidationEmployeeOtherEmailAPITest.php
src/plugins/orangehrmPimPlugin/test/Dao/EmployeeDaoTest.php
src/plugins/orangehrmPimPlugin/test/fixtures/EmployeeContactDetailsAPI.yml
src/plugins/orangehrmPimPlugin/test/fixtures/EmployeeOtherEmailValidation.yml
src/plugins/orangehrmPimPlugin/test/fixtures/EmployeeWorkEmailValidation.yml
src/plugins/orangehrmPimPlugin/test/fixtures/testcases/EmployeeContactDetailsAPITestCases.yaml
src/plugins/orangehrmPimPlugin/test/fixtures/testcases/EmployeeOtherEmailValidationTestCase.yaml
src/plugins/orangehrmPimPlugin/test/fixtures/testcases/EmployeeWorkEmailValidationTestCase.yaml
src/plugins/orangehrmTimePlugin/Api/ValidateProjectNameAPI.php
src/plugins/orangehrmTimePlugin/Api/ValidationCustomerNameAPI.php

PR contains:
- OHRM5X-1271: [Broken][PIM- Contact Details] Already existing email address (Work or Other) or same employee's work email can be entered to the other email field.
- OHRM5X-1268: [Project Info][Broken] "Invalid parameter" toast message is displaying when user type a name with more than 50 characters.

OHRM5X-1271: Validation for Employee Other Email

---

src/client/src/core/util/services/api.service.ts
src/client/src/orangehrmAdminPlugin/pages/systemUser/EditSystemUser.vue
src/client/src/orangehrmAdminPlugin/pages/systemUser/SaveSystemUser.vue
src/client/src/orangehrmLeavePlugin/components/LeaveBalance.vue
src/client/src/orangehrmLeavePlugin/pages/entitlements/EditEntitlement.vue
src/client/src/orangehrmPimPlugin/pages/employee/EmployeeContactDetails.vue
src/client/src/orangehrmTimePlugin/components/AddCustomerModal.vue
src/client/src/orangehrmTimePlugin/pages/customer/EditCustomer.vue
src/client/src/orangehrmTimePlugin/pages/customer/SaveCustomer.vue
src/client/src/orangehrmTimePlugin/pages/project/ProjectEdit.vue
src/client/src/orangehrmTimePlugin/pages/project/ProjectSave.vue
src/plugins/orangehrmAdminPlugin/Api/ValidationUserNameAPI.php
src/plugins/orangehrmPimPlugin/Api/ValidationEmployeeEmailAPI.php
src/plugins/orangehrmPimPlugin/Api/ValidationEmployeeOtherEmailAPI.php
src/plugins/orangehrmTimePlugin/Api/ValidateProjectNameAPI.php
src/plugins/orangehrmTimePlugin/Api/ValidationCustomerNameAPI.php

PR contains:
- OHRM5X-1264: [Broken-5beta][Leave- Apply Leave]"Invalid parameter" error message is displayed when the user selects a value from the partial days dropdown.

OHRM5X-1264: Prevent Showing Invalid Parameter Toast

---

installer/Migration/V5_0_0/lang-string/pim.yaml
src/client/src/core/util/validation/__tests__/rules.spec.ts
src/client/src/core/util/validation/rules.ts
src/client/src/orangehrmPimPlugin/components/EditMembership.vue
src/client/src/orangehrmPimPlugin/components/EditSalaryComponent.vue
src/client/src/orangehrmPimPlugin/components/SaveMembership.vue
src/client/src/orangehrmPimPlugin/components/SaveSalaryComponent.vue
src/client/src/orangehrmPimPlugin/pages/employee/EmployeeContactDetails.vue
src/plugins/orangehrmAdminPlugin/Api/ModulesAPI.php
src/plugins/orangehrmAdminPlugin/test/Api/ModulesAPITest.php
src/plugins/orangehrmAdminPlugin/test/fixtures/ModuleDao.yml
src/plugins/orangehrmCorePlugin/Service/MenuService.php

PR contains:
- OHRM5X-1265: [Broken-5beta][Menu- Side Panel] Changes in the side panel is not displayed after enabling/disabling the modules.
- OHRM5X-1271: Reopen issue
- OHRM5X-1277: [Broken][PIM - Memberships] "Required" validation message is not getting displayed when user click save without selecting a membership

OHRM5X-1265: Invalidate Cache when Configuring Modules

---

src/client/src/orangehrmLeavePlugin/pages/LeaveApply.vue
src/client/src/orangehrmLeavePlugin/util/composable/useLeaveValidators.ts
src/client/src/orangehrmTimePlugin/components/Timesheet.vue
src/client/src/orangehrmTimePlugin/pages/timesheets/EditTimeSheet.vue

PR contains:
- OHRM5X-1296: [Broken-5beta][Timesheets] Broken Issues in My/Employee Timesheets
- OHRM5X-1297: [Broken-4x][Apply Leave] Error toast message is displayed when user applies leave for multiple days by selecting partial days option.

OHRM5X-1296: Fix for Broken Timesheet

---

installer/Controller/Installer/AdminUserCreationController.php
installer/client/src/core/util/validation/rules.ts
installer/client/src/pages/AdminUserCreation.vue
installer/config/routes.yaml

PR contains:
- OHRM5X-1300: [Installer][FE] Admin User Creation

OHRM5X-1300: Admin User Creation for Installer

---

.github/workflows/cypress.yml
src/client/src/orangehrmLeavePlugin/util/composable/useLeaveValidators.ts

PR contains:
- OHRM5X-1297: Reopened issue
- Issue was fixed for leave validation but not for submitting on Leave Apply/Assign screens.

OHRM5X-1297: Prevent Internal Server Error on Leave Apply/Assign

---

installer/Controller/Installer/Api/DatabaseConfigAPI.php
installer/Controller/Upgrader/Api/DatabaseConfigAPI.php
installer/Util/AppSetupUtility.php
installer/Util/Messages.php
installer/Util/UpgraderConfigUtility.php
src/plugins/orangehrmAuthenticationPlugin/Controller/LoginController.php

This PR contains:
OHRM5X-1318 Bug fix
OHRM5X-1324 Bug fix

OHRM5X-1318: Fixes for Incorrect Validation Messages are displayed in Database Configuration Screen

---

installer/client/src/components/installer-layout.scss
installer/client/src/core/util/composable/useBeforeUnload.ts
installer/client/src/core/util/directives/tooltip.ts
installer/client/src/core/util/validation/rules.ts
installer/client/src/pages/AdminUserCreationScreen.vue
installer/client/src/pages/CurrentVersionScreen.vue
installer/client/src/pages/DatabaseConfigScreen.vue
installer/client/src/pages/InstallScreen.vue
installer/client/src/pages/InstanceCreationScreen.vue
installer/client/src/pages/LicenceAcceptanceScreen.vue
installer/client/src/pages/UpgradeScreen.vue

- OHRM5X-1327: Installer - DB name validations added
- OHRM5X-1319: Installer - Refactor install process, show error message of failure
- OHRM5X-1299: Upgrader - current version details dropdown required validation fix
- OHRM5X-1319: Installer - DB Config screen style fixes, layout style fixes
- OHRM5X-1323: Installer - Organization name length validation fix
- OHRM5X-1319: Installer - Licence acceptance remove required text
- OHRM5X-1317: Installer - Installation steps renamed
- OHRM5X-1322: Installer - admin user creation email length validation fix

OHRM5X-320: Installer defect fixes

---

installer/Migration/V5_0_0/translation/de.yaml
src/client/src/orangehrmLeavePlugin/util/composable/useLeaveActions.ts

- OHRM5X-1329: Leave - Leave list action buttons alignment fixes
- OHRM5X-1202: Core - Fix German language strings

OHRM5X-320: Localisation defect fixes

---

src/client/src/core/util/composable/useInfiniteScroll.ts
src/client/src/core/util/composable/usePaginate.ts

Code Example - https://gist.github.com/Super-Chama/d7ec4d9e4c19232b3b14fbc3dee271a1

OHRM5X-1384: Core - Infinite scoll composable added

---

installer/Migration/V5_1_0/permission/api.yaml
src/client/src/orangehrmRecruitmentPlugin/components/CandidateStatusDropdown.vue
src/plugins/orangehrmRecruitmentPlugin/Api/CandidateAllowedActionsAPI.php
src/plugins/orangehrmRecruitmentPlugin/Api/CandidateStatusAPI.php
src/plugins/orangehrmRecruitmentPlugin/config/routes.yaml
src/plugins/orangehrmRecruitmentPlugin/entity/CandidateHistory.php
src/plugins/orangehrmRecruitmentPlugin/entity/Decorator/CandidateHistoryDecorator.php
src/plugins/orangehrmRecruitmentPlugin/entity/Decorator/InterviewAttachmentDecorator.php
src/plugins/orangehrmRecruitmentPlugin/entity/Decorator/InterviewDecorator.php
src/plugins/orangehrmRecruitmentPlugin/entity/Interview.php
src/plugins/orangehrmRecruitmentPlugin/entity/InterviewAttachment.php
src/plugins/orangehrmRecruitmentPlugin/entity/Vacancy.php
src/plugins/orangehrmRecruitmentPlugin/entity/VacancyAttachment.php
src/plugins/orangehrmRecruitmentPlugin/test/Api/CandidateAllowedActionsAPITest.php
src/plugins/orangehrmRecruitmentPlugin/test/Entity/CandidateAttachmentTest.php
src/plugins/orangehrmRecruitmentPlugin/test/Entity/VacancyAttachmentTest.php
src/plugins/orangehrmRecruitmentPlugin/test/fixtures/CandidateVacancy.yaml
src/plugins/orangehrmRecruitmentPlugin/test/fixtures/testcases/CandidateAllowedActionsTestCases.yaml

Entities:-
- CandidateHistory
- Interview
- InterviewAttachment
API to get allowed candidate actions

OHRM5X-1359: Candidate Workflow

---

installer/Migration/V5_1_0/Migration.php
installer/Migration/V5_1_0/lang-string/performance.yaml
src/client/src/orangehrmPerformancePlugin/pages/AddReview.vue
src/client/src/orangehrmPerformancePlugin/pages/EditReview.vue
src/client/src/orangehrmPerformancePlugin/pages/MyReviews.vue
src/client/src/orangehrmPerformancePlugin/pages/ReviewSearch.vue
src/plugins/orangehrmPerformancePlugin/config/routes.yaml

Fixed loading bug
Fixed FE validation not being enforced for required.

OHRM5X-1439 : Fix Bug page keeps loading after displaying error toast message

---

devTools/core/src/Command/AddTestTranslationCommand.php
devTools/core/src/Command/Util/TranslationTestTool.php
src/client/src/orangehrmPerformancePlugin/pages/AddReview.vue
src/client/src/orangehrmPerformancePlugin/pages/EditReview.vue
src/client/src/orangehrmPerformancePlugin/pages/MyTracker.vue
src/client/src/orangehrmPerformancePlugin/pages/PerformanceTrackers.vue
src/client/src/orangehrmPerformancePlugin/pages/review.scss
src/client/src/orangehrmPimPlugin/components/EmployeeSubordinates.vue
src/client/src/orangehrmPimPlugin/components/EmployeeSupervisors.vue
src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php
src/plugins/orangehrmPerformancePlugin/Dao/PerformanceReviewDao.php
src/plugins/orangehrmPerformancePlugin/Dao/PerformanceTrackerDao.php
src/plugins/orangehrmPerformancePlugin/Exception/ReviewServiceException.php
src/plugins/orangehrmPerformancePlugin/Service/PerformanceReviewService.php

… add button
OHRM5X-1443 : Validation and toast messages related defects
OHRM5X-1444 : User can select a past employee as the reviewer
OHRM5X-1446 : All 3 buttons should have the same width.

OHRM5X-1440: Fix performance - add review, my tracker related issues

---

installer/Migration/V5_1_0/Migration.php
installer/Migration/V5_1_0/permission/api.yaml
src/plugins/orangehrmCorePlugin/Authorization/UserRole/EssUserRole.php
src/plugins/orangehrmPerformancePlugin/Api/Model/CompletedPerformanceReviewModel.php
src/plugins/orangehrmPerformancePlugin/Api/PerformanceReviewFinalEvaluationAPI.php
src/plugins/orangehrmPerformancePlugin/Dao/PerformanceReviewDao.php
src/plugins/orangehrmPerformancePlugin/Dao/PerformanceTrackerDao.php
src/plugins/orangehrmPerformancePlugin/Dao/PerformanceTrackerLogDao.php
src/plugins/orangehrmPerformancePlugin/config/routes.yaml
src/plugins/orangehrmPerformancePlugin/entity/Decorator/PerformanceReviewDecorator.php
src/plugins/orangehrmPerformancePlugin/entity/PerformanceReview.php
src/plugins/orangehrmPerformancePlugin/test/Api/PerformanceReviewFinalEvaluationAPITest.php
src/plugins/orangehrmPerformancePlugin/test/fixtures/PerformanceReviewFinalEvaluationAPITest.yaml
src/plugins/orangehrmPerformancePlugin/test/fixtures/testcases/PerformanceReviewFinalEvaluationAPITestCases.yaml

PR contains:
- OHRM5X-1453: [API] Final evaluation
- OHRM5X-1432: reopen fix

OHRM5X-1453: Develop performance - final evaluation API

---

src/client/src/orangehrmPerformancePlugin/components/tracker-log-card.scss
src/client/src/orangehrmPerformancePlugin/pages/EmployeeTrackers.vue
src/client/src/orangehrmPerformancePlugin/pages/KpiSearch.vue
src/client/src/orangehrmPerformancePlugin/pages/ReviewSearch.vue
src/client/src/orangehrmPerformancePlugin/pages/employee-tracker-log.scss

- OHRM5X-1430: [Performance-Manage Reviews] UI issues related to the list view table.
- OHRM5X-1395: [Performance-KPIs] List view action buttons are not aligned properly.
- OHRM5X-1476: [Performance- Employee Tracker][Mobile] User unable to view or add logs for employees
- OHRM5X-1465: [Performance- Tracker logs] Add performance tracker logs screen UI issues.
Review evaluation commits move to [separate PR](https://github.com/Super-Chama/orangehrm/pull/54)

OHRM5X-1395: Fix performance - trackers, tracker logs related issues

---

installer/Migration/V5_1_0/Migration.php
installer/Migration/V5_1_0/lang-string/maintenance.yaml
src/client/src/orangehrmMaintenancePlugin/components/CandidateRecords.vue
src/client/src/orangehrmMaintenancePlugin/components/SelectedCandidates.vue
src/client/src/orangehrmMaintenancePlugin/components/VacancyAutocomplete.vue
src/client/src/orangehrmMaintenancePlugin/index.ts
src/client/src/orangehrmMaintenancePlugin/pages/PurgeCandidate.vue
src/plugins/orangehrmMaintenancePlugin/Api/Model/PurgeCandidateListModel.php
src/plugins/orangehrmMaintenancePlugin/Api/PurgeCandidateAPI.php
src/plugins/orangehrmMaintenancePlugin/Controller/PurgeCandidateController.php
src/plugins/orangehrmMaintenancePlugin/config/routes.yaml
src/plugins/orangehrmMaintenancePlugin/test/Api/PurgeCandidateAPITest.php
src/plugins/orangehrmMaintenancePlugin/test/fixtures/PurgeCandidateAPITest.yml
src/plugins/orangehrmMaintenancePlugin/test/fixtures/testcases/PurgeCandidateAPITestCases.yml
src/plugins/orangehrmRecruitmentPlugin/Api/VacancyAPI.php
src/plugins/orangehrmRecruitmentPlugin/Dao/CandidateDao.php
src/plugins/orangehrmRecruitmentPlugin/Dao/VacancyDao.php
src/plugins/orangehrmRecruitmentPlugin/Dto/CandidateSearchFilterParams.php
src/plugins/orangehrmRecruitmentPlugin/Dto/VacancySearchFilterParams.php
src/plugins/orangehrmRecruitmentPlugin/test/fixtures/testcases/VacancyTestCases.yaml

PR contains:
- OHRM5X-1530: FE - Purge Candidates

OHRM5X-1530: Develop maintenance - purge candidate screen

---

src/client/src/orangehrmRecruitmentPlugin/pages/AddJobVacancy.vue
src/client/src/orangehrmRecruitmentPlugin/pages/EditJobVacancy.vue
src/plugins/orangehrmCorePlugin/Authorization/UserRole/AdminUserRole.php
src/plugins/orangehrmCorePlugin/Authorization/UserRole/HiringManagerUserRole.php
src/plugins/orangehrmCorePlugin/Authorization/UserRole/InterviewerUserRole.php
src/plugins/orangehrmRecruitmentPlugin/Api/CandidateHistoryAPI.php
src/plugins/orangehrmRecruitmentPlugin/Api/CandidateInterviewSchedulingAPI.php
src/plugins/orangehrmRecruitmentPlugin/Api/VacancyAPI.php
src/plugins/orangehrmRecruitmentPlugin/Controller/WorkflowActionHistoryController.php
src/plugins/orangehrmRecruitmentPlugin/Dao/CandidateDao.php
src/plugins/orangehrmRecruitmentPlugin/Dao/RecruitmentAttachmentDao.php
src/plugins/orangehrmRecruitmentPlugin/Dao/VacancyDao.php
src/plugins/orangehrmRecruitmentPlugin/test/fixtures/JobVacancyDao.yaml
src/plugins/orangehrmRecruitmentPlugin/test/fixtures/testcases/VacancyTestCases.yaml

This PR Contains:-
- OHRM5X-1555
- OHRM5X-1556 
- OHRM5X-1539 
- OHRM5X-1566 
- OHRM5X-1593
- OHRM5X-1408

OHRM5X-1555: Fix recruitment - candidate, vacancy related issues

---

installer/client/package.json
installer/client/yarn.lock
src/client/package.json
src/client/yarn.lock
src/plugins/orangehrmRecruitmentPlugin/Api/CandidateAPI.php
src/plugins/orangehrmRecruitmentPlugin/Controller/WorkflowActionHistoryController.php
src/plugins/orangehrmRecruitmentPlugin/Dao/CandidateDao.php

* OHRM5X-1626: Candidate vacancy related issue fixes
* OHRM5X-1628: Bump oxd version to 1.0.6

OHRM5X-1628: Bump oxd version to 1.0.6

---

devTools/core/src/Command/ResetInstallationCommand.php
installer/Controller/Installer/Api/ConfigFileAPI.php
installer/Controller/Installer/Api/DatabaseConfigAPI.php
installer/Util/AppSetupUtility.php
installer/Util/StateContainer.php
installer/cli_install.php
installer/cli_install_config.yaml
installer/client/src/pages/ConfirmationScreen.vue
installer/client/src/pages/DatabaseConfigScreen.vue
phpunit.xml
src/composer.json
src/composer.lock
src/plugins/orangehrmAdminPlugin/entity/EmailConfiguration.php
src/plugins/orangehrmAdminPlugin/entity/Listener/EmailConfigurationListener.php
src/plugins/orangehrmCorePlugin/Exception/KeyHandlerException.php
src/plugins/orangehrmCorePlugin/Utility/Cryptographer.php
src/plugins/orangehrmCorePlugin/Utility/KeyHandler.php
src/plugins/orangehrmCorePlugin/entity/Listener/BaseListener.php
src/plugins/orangehrmCorePlugin/test/Utility/CryptographerTest.php
src/plugins/orangehrmPimPlugin/entity/Employee.php
src/plugins/orangehrmPimPlugin/entity/EmployeeSalary.php
src/plugins/orangehrmPimPlugin/entity/Listener/EmployeeListener.php
src/plugins/orangehrmPimPlugin/entity/Listener/EmployeeSalaryListener.php

PR contains:
- OHRM5X-1604: Support encryption of fields when installing the system
- OHRM5X-825: [BE] Handle PIM report encrypted fields

OHRM5X-1604: Develop installer - encryption

---

src/plugins/orangehrmCorePlugin/Service/DateTimeHelperService.php
src/plugins/orangehrmCorePlugin/test/Service/DateTimeHelperServiceTest.php
src/plugins/orangehrmDashboardPlugin/Dao/EmployeeTimeAtWorkDao.php
src/plugins/orangehrmDashboardPlugin/Service/EmployeeTimeAtWorkService.php
src/plugins/orangehrmTimePlugin/Service/TimesheetService.php

This PR Contains:
- Bug Fix - OHRM5X-1727
- Bug Fix - OHRM5X-1763
- Review Feedback Fix - OHRM5X-1723

OHRM5X-1727: Fix Week Boundary Related Issues

---

installer/Controller/Upgrader/Api/SystemCheckAPI.php
installer/Util/SystemConfig.php
src/plugins/orangehrmDashboardPlugin/Api/EmployeeOnLeaveTodayConfigAPI.php
src/plugins/orangehrmDashboardPlugin/Api/Model/EmployeesOnLeaveListModel.php
src/plugins/orangehrmDashboardPlugin/Dao/EmployeeActionSummaryDao.php
src/plugins/orangehrmDashboardPlugin/Dto/EmployeeOnLeaveSearchFilterParams.php
src/plugins/orangehrmDashboardPlugin/test/Api/EmployeeOnLeaveApiTest.php
src/plugins/orangehrmDashboardPlugin/test/Dao/EmployeeOnLeaveDaoTest.php
src/plugins/orangehrmDashboardPlugin/test/fixtures/EmployeeOnLeaveDao.yml
src/plugins/orangehrmDashboardPlugin/test/fixtures/testcases/EmployeeOnLeaveAPITestCases.yaml

This PR Contains:-
- OHRM5X-1687 - Develop Ldap Extension check in Installer
- OHRM5X-1751 - Add Unit tests
- OHRM5X-1752 - Bug Fix

OHRM5X-1687: Check installer - LDAP extension

---

bin/console
build/build.xml
installer/Controller/Upgrader/Api/ConfigFileAPI.php
installer/Controller/Upgrader/Api/SystemCheckAPI.php
installer/Exception/SessionStorageNotWritable.php
installer/Framework/HttpKernel.php
installer/Util/SystemConfig.php
installer/cli_install.php
installer/index.php
src/composer.json
src/lib/config/Config.php
src/lib/config/ConfigHelper.php
src/lib/orm/Doctrine.php
src/plugins/orangehrmCoreOAuthPlugin/entity/OAuthScope.php
src/plugins/orangehrmCorePlugin/Command/CacheClearCommand.php
src/plugins/orangehrmCorePlugin/Command/GenerateDoctrineProxiesCommand.php
src/plugins/orangehrmCorePlugin/Controller/AbstractVueController.php
src/plugins/orangehrmCorePlugin/Subscriber/SessionSubscriber.php
src/plugins/orangehrmCorePlugin/config/CorePluginConfiguration.php
src/plugins/orangehrmI18NPlugin/Controller/I18NMessagesController.php

OHRM5X-1805: Generate doctrine proxy classes

---

installer/Migration/V5_3_0/permission/api.yaml
src/plugins/orangehrmBuzzPlugin/Api/BuzzLikeOnCommentAPI.php
src/plugins/orangehrmBuzzPlugin/Api/BuzzLikeOnShareAPI.php
src/plugins/orangehrmBuzzPlugin/Api/Model/BuzzLikeOnCommentModel.php
src/plugins/orangehrmBuzzPlugin/Dao/BuzzLikeDao.php
src/plugins/orangehrmBuzzPlugin/Dto/BuzzLikeOnCommentSearchFilterParams.php
src/plugins/orangehrmBuzzPlugin/Dto/BuzzLikeOnShareSearchFilterParams.php
src/plugins/orangehrmBuzzPlugin/config/routes.yaml
src/plugins/orangehrmBuzzPlugin/entity/BuzzLikeOnComment.php
src/plugins/orangehrmBuzzPlugin/entity/Decorator/BuzzCommentDecorator.php
src/plugins/orangehrmBuzzPlugin/entity/Decorator/BuzzLikeOnCommentDecorator.php
src/plugins/orangehrmBuzzPlugin/test/Api/BuzzLikeOnCommentAPITest.php
src/plugins/orangehrmBuzzPlugin/test/Dao/BuzzLikeDaoTest.php
src/plugins/orangehrmBuzzPlugin/test/fixtures/BuzzLikeOnCommentAPI.yaml
src/plugins/orangehrmBuzzPlugin/test/fixtures/testcases/BuzzLikeOnCommentAPITestCases.yaml

PR contains:
- OHRM5X-1846: [BE][API] Comment Likes API::getAll
- OHRM5X-1847: [BE][API] Comment Likes API::create
- OHRM5X-1848: [BE][API] Comment Likes API::update

OHRM5X-1846: Develop buzz - likes on comment API

---

src/plugins/orangehrmBuzzPlugin/Api/BuzzShareAPI.php
src/plugins/orangehrmBuzzPlugin/Dao/BuzzDao.php
src/plugins/orangehrmBuzzPlugin/config/routes.yaml
src/plugins/orangehrmBuzzPlugin/test/Api/BuzzShareAPITest.php
src/plugins/orangehrmBuzzPlugin/test/Dao/BuzzDaoTest.php
src/plugins/orangehrmBuzzPlugin/test/fixtures/BuzzShareAPI.yaml
src/plugins/orangehrmBuzzPlugin/test/fixtures/testcases/BuzzShareAPITestCases.yaml
src/plugins/orangehrmCorePlugin/Authorization/UserRole/AdminUserRole.php
src/plugins/orangehrmCorePlugin/Authorization/UserRole/EssUserRole.php

PR contains:
- OHRM5X-1831: [BE][API] Share API::delete

OHRM5X-1831: Develop buzz - share API delete

---

installer/Migration/V5_3_0/permission/api.yaml
src/plugins/orangehrmBuzzPlugin/Api/BuzzPostShareAPI.php
src/plugins/orangehrmBuzzPlugin/Dao/BuzzDao.php
src/plugins/orangehrmBuzzPlugin/Dto/BuzzPostShareSearchFilterParams.php
src/plugins/orangehrmBuzzPlugin/config/routes.yaml
src/plugins/orangehrmBuzzPlugin/test/Api/BuzzPostShareAPITest.php
src/plugins/orangehrmBuzzPlugin/test/Dao/BuzzDaoTest.php
src/plugins/orangehrmBuzzPlugin/test/fixtures/BuzzPostShareAPITest.yaml
src/plugins/orangehrmBuzzPlugin/test/fixtures/testcases/BuzzPostShareAPITestCases.yaml

PR contains:
- OHRM5X-1823: [BE][API] Share Shares API::getAll

OHRM5X-1823: Develop buzz - post share API get operation

---

src/plugins/orangehrmMaintenancePlugin/AccessStrategy/AccessStrategy.php
src/plugins/orangehrmMaintenancePlugin/config/gdpr_access_employee_strategy.yml
src/plugins/orangehrmMaintenancePlugin/test/Service/MaintenanceServiceTest.php
src/plugins/orangehrmMaintenancePlugin/test/Service/PurgeServiceTest.php
src/plugins/orangehrmMaintenancePlugin/test/fixtures/EmployeeMaintenence.yml
src/plugins/orangehrmMaintenancePlugin/test/fixtures/PurgeService.yml

PR contains: 
- OHRM5X-1880: Handle GDPR Access Records
- OHRM5X-1816: Handle GDPR Purging

OHRM5X-1880: Develop maintenance - employee access buzz data

---

installer/Migration/V5_4_0/Migration.php
installer/Migration/V5_4_0/lang-string/admin.yaml
src/client/src/orangehrmCoreOAuthPlugin/pages/registerOAuthClient/EditOAuthClient.vue
src/client/src/orangehrmCoreOAuthPlugin/pages/registerOAuthClient/OAuthClient.vue
src/client/src/orangehrmCoreOAuthPlugin/pages/registerOAuthClient/SaveOAuthClient.vue
src/client/src/orangehrmCoreOAuthPlugin/pages/registerOAuthClient/oauth-client.scss
src/lib/framework/Services.php
src/plugins/orangehrmAdminPlugin/Api/ModulesAPI.php
src/plugins/orangehrmAdminPlugin/config/routes.yaml
src/plugins/orangehrmCoreOAuthPlugin/Api/Model/OAuthClientModel.php
src/plugins/orangehrmCoreOAuthPlugin/Api/OAuthClientAPI.php
src/plugins/orangehrmCoreOAuthPlugin/Controller/SaveOAuthClientController.php
src/plugins/orangehrmCoreOAuthPlugin/Dao/OAuthClientDao.php
src/plugins/orangehrmCoreOAuthPlugin/Dto/Entity/ClientEntity.php
src/plugins/orangehrmCoreOAuthPlugin/Dto/OAuthClientSearchFilterParams.php
src/plugins/orangehrmCoreOAuthPlugin/Service/OAuthService.php
src/plugins/orangehrmCoreOAuthPlugin/Traits/OAuthServiceTrait.php
src/plugins/orangehrmCoreOAuthPlugin/config/CoreOAuthPluginConfiguration.php
src/plugins/orangehrmCoreOAuthPlugin/config/routes.yaml
src/plugins/orangehrmCoreOAuthPlugin/entity/OAuthClient.php
src/plugins/orangehrmCoreOAuthPlugin/test/Api/Model/OAuthClientModelTest.php
src/plugins/orangehrmCoreOAuthPlugin/test/Api/OAuthClientAPITest.php
src/plugins/orangehrmCoreOAuthPlugin/test/Dao/OAuthClientDaoTest.php
src/plugins/orangehrmCoreOAuthPlugin/test/Entity/OAuthClientTest.php
src/plugins/orangehrmCoreOAuthPlugin/test/Service/OAuthServiceTest.php
src/plugins/orangehrmCoreOAuthPlugin/test/fixtures/OAuthClientAPITest.yaml
src/plugins/orangehrmCoreOAuthPlugin/test/fixtures/testcases/OAuthClientAPITestCases.yaml

PR contains:
- OHRM5X-2069: [BE][API] Register OAuth 2 app
- OHRM5X-2070: [FE] Register OAuth 2 app
FE Screenshots:
List view
Add screen
Edit screen

OHRM5X-2069: Develop OAuth - Register OAuth2 App FE/BE

---

installer/Migration/V5_4_0/lang-string/auth.yaml
src/client/src/orangehrmCoreOAuthPlugin/pages/oauth/OAuthAuthorize.vue
src/client/src/orangehrmCoreOAuthPlugin/pages/oauth/oauth-authorize.scss
src/plugins/orangehrmCoreOAuthPlugin/Api/OAuthClientAPI.php
src/plugins/orangehrmCoreOAuthPlugin/Controller/AuthorizationController.php
src/plugins/orangehrmCoreOAuthPlugin/test/fixtures/testcases/OAuthClientAPITestCases.yaml

PR contains:
- OHRM5X-2066: [FE] Develop consent screen
Updated SS in a comment below
Mobile View
Mobile View - Invalid Request
Web View
Web View - Invalid Request

OHRM5X-2066: Develop oauth - consent screen FE

---

installer/Migration/V5_4_0/lang-string/auth.yaml
src/client/src/orangehrmAdminPlugin/pages/moduleConfiguration/EditModuleConfiguration.vue
src/client/src/orangehrmCoreOAuthPlugin/pages/oauth/OAuthAuthorize.vue
src/plugins/orangehrmAdminPlugin/Api/ModulesAPI.php
src/plugins/orangehrmAdminPlugin/test/fixtures/ModulesAPI.yaml
src/plugins/orangehrmAdminPlugin/test/fixtures/testcases/ModulesAPITestCases.yaml
src/plugins/orangehrmCoreOAuthPlugin/Api/OAuthClientAPI.php
src/plugins/orangehrmCoreOAuthPlugin/Dao/OAuthClientDao.php
src/plugins/orangehrmCoreOAuthPlugin/Service/OAuthService.php
src/plugins/orangehrmCoreOAuthPlugin/test/fixtures/OAuthClientAPITest.yaml
src/plugins/orangehrmCoreOAuthPlugin/test/fixtures/testcases/OAuthClientAPITestCases.yaml

PR contains:
- OHRM5X-2112: Enable/Disable Mobile Module from Admin > Configuration > Modules
Mobile Disabled Error Screen

OHRM5X-2112: Fix oauth - mobile client restrict

---

.github/workflows/test.yml
src/plugins/orangehrmMaintenancePlugin/Service/PurgeService.php
src/plugins/orangehrmMaintenancePlugin/test/Service/PurgeServiceTest.php
src/plugins/orangehrmMaintenancePlugin/test/fixtures/testcases/PurgeEmployeeAPITestCases.yml
src/plugins/orangehrmPimPlugin/Api/EmployeePictureAPI.php
src/plugins/orangehrmPimPlugin/Controller/File/EmployeePictureController.php
src/plugins/orangehrmPimPlugin/Service/EmployeePictureService.php
src/plugins/orangehrmPimPlugin/test/Service/EmployeePictureServiceTest.php

PR contains:
- OHRM5X-2140: [BE] Cache employee profile picture

OHRM5X-2140: Develop employee picture - add etag caching

---

installer/Migration/V5_5_0/Migration.php
installer/Migration/V5_6_0/Migration.php
installer/Util/AppSetupUtility.php
installer/client/src/core/util/composable/useProgress.ts
src/lib/config/Config.php
src/plugins/orangehrmCorePlugin/test/fixtures/testcases/AboutOrganizationTestCase.yaml

PR contains:
- OHRM5X-2273 (fix for https://github.com/orangehrm/orangehrm/issues/1717)
- OHRM5X-2274 (fix for https://github.com/orangehrm/orangehrm/issues/1716)

OHRM5X-2273: Fix installer - prevent next button showing early

---

installer/Migration/V4_3_3/Migration.php
src/plugins/orangehrmLeavePlugin/test/Dao/LeaveRequestDaoTest.php

PR contains:
- OHRM5X-2294: MariaDB Install Failure #1731

OHRM5X-2294: Fix installer - MariaDB install failure

---

build/build.xml
installer/Migration/V5_3_0/Migration.php
installer/client/src/components/DatabaseConfigDialog.vue
src/client/src/orangehrmAdminPlugin/pages/jobTitle/EditJobTitle.vue
src/client/src/orangehrmAdminPlugin/pages/jobTitle/SaveJobTitle.vue
src/client/src/orangehrmAdminPlugin/pages/qualificationSkill/EditQualificationSkill.vue
src/plugins/orangehrmCorePlugin/Api/Rest/ValidationUniqueAPI.php

PR contains:
- OHRM5X-2420: MariaDB Installer Failure in Migration 5.3
- OHRM5X-2448: [Broken][Admin][Job Title] When adiing a same job title which has already deleted , "Gives Already excist " message
- OHRM5X-2449: [Broken][Admin][Skills] Without editing the skill name , Unable to save other changes
- OHRM5X-2302: [5.6] 5.6 zip file name and upgrade warning content need to update

OHRM5X-2420: CRB and Defect Fixes

---

src/composer.json
src/plugins/orangehrmAuthenticationPlugin/Auth/User.php
src/plugins/orangehrmCorePlugin/Service/EmailService.php
src/plugins/orangehrmCorePlugin/Subscriber/MailerSubscriber.php

PR contains:
- OHRM5X-2318: Mobile Email Notification Delay

OHRM5X-2318: Fix email notification delay when action performed from mobile

---

.github/workflows/scheduled_test.yml

PR contains:
- OHRM5X-2466: Update scheduled tests

OHRM5X-2466: Bump scheduled tests PHP, MySQL, MariaDB versions

---

.github/workflows/scheduled_test.yml
.github/workflows/test.yml
installer/Migration/V5_7_0/Migration.php
installer/Util/DatabaseUserPermissionEvaluator.php
src/plugins/orangehrmAdminPlugin/Dao/LocationDao.php
src/plugins/orangehrmAdminPlugin/entity/Language.php
src/plugins/orangehrmAttendancePlugin/Dao/AttendanceDao.php
src/plugins/orangehrmCorePlugin/Dao/ReportGeneratorDao.php
src/plugins/orangehrmCorePlugin/Report/DisplayField/GenericBasicDisplayField.php
src/plugins/orangehrmCorePlugin/Report/DisplayField/GenericBasicDisplayFieldWithAggregate.php
src/plugins/orangehrmCorePlugin/Report/DisplayField/GenericDateDisplayFieldWithAggregate.php
src/plugins/orangehrmCorePlugin/Report/DisplayField/GenericDateDisplayFieldWithAggregateDTO.php
src/plugins/orangehrmLDAPAuthenticationPlugin/Dao/LDAPDao.php
src/plugins/orangehrmLeavePlugin/Dao/LeaveEntitlementDao.php
src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php
src/plugins/orangehrmLeavePlugin/Dto/LeaveRequestSearchFilterParams.php
src/plugins/orangehrmLeavePlugin/Service/LeaveRequestService.php
src/plugins/orangehrmPimPlugin/Dao/EmployeeLanguageDao.php
src/plugins/orangehrmPimPlugin/Dto/EmployeeAllowedLanguageSearchFilterParams.php
src/plugins/orangehrmRecruitmentPlugin/Api/HiringManagerAPI.php
src/plugins/orangehrmRecruitmentPlugin/Dao/VacancyDao.php
src/plugins/orangehrmRecruitmentPlugin/test/Dao/VacancyDaoTest.php
src/plugins/orangehrmTimePlugin/Dao/ProjectActivityDao.php
src/plugins/orangehrmTimePlugin/Dao/ProjectDao.php
src/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
src/plugins/orangehrmTimePlugin/Report/EmployeeReportData.php
src/plugins/orangehrmTimePlugin/test/Dao/TimesheetDaoTest.php

PR contains:
- OHRM5X-2335: Fix Group By Installer Failure
[Research](https://docs.google.com/document/d/1hdc883exY_0rYL-waHZMn9RAA6bJ86PMa1kYkCdaGjU/edit#heading=h.fpex38c77zzb)

OHRM5X-2335: Group By Fix

---

.github/workflows/docker_build.yml
Dockerfile
installer/client/package.json
installer/client/yarn.lock
src/client/package.json
src/client/yarn.lock

PR contains:
- OHRM5X-2418: Upgrade OrangeHRM docker container PHP and Apache version
- OHRM5X-2497: [OXD] Update libraries with security alerts

OHRM5X-2418: Bump docker image

---

CHANGELOG.TXT

PR contains:
- OHRM5X-2539: Update changelog

OHRM5X-2539: Update Changelog

---

build/build.xml

`exec command` is now deprecated in `phing`. See https://github.com/phingofficial/phing/blob/main/UPGRADING.md?plain=1#L90-L96

OHRM5X-2561: Fix build failure

---

.github/workflows/4x_dumps/V4_0.sql
.github/workflows/4x_dumps/V4_1.sql
.github/workflows/4x_dumps/V4_10.sql
.github/workflows/4x_dumps/V4_10_1.sql
.github/workflows/4x_dumps/V4_1_1.sql
.github/workflows/4x_dumps/V4_1_2.sql
.github/workflows/4x_dumps/V4_1_2_1.sql
.github/workflows/4x_dumps/V4_2_0_1.sql
.github/workflows/4x_dumps/V4_3.sql
.github/workflows/4x_dumps/V4_3_1.sql
.github/workflows/4x_dumps/V4_3_2.sql
.github/workflows/4x_dumps/V4_3_3.sql
.github/workflows/4x_dumps/V4_3_4.sql
.github/workflows/4x_dumps/V4_3_5.sql
.github/workflows/4x_dumps/V4_4.sql
.github/workflows/4x_dumps/V4_5.sql
.github/workflows/4x_dumps/V4_6.sql
.github/workflows/4x_dumps/V4_6_0_1.sql
.github/workflows/4x_dumps/V4_7.sql
.github/workflows/4x_dumps/V4_8.sql
.github/workflows/4x_dumps/V4_9.sql
.github/workflows/4x_upgrade_test.yml
installer/Migration/V4_3_3/Migration.php
src/plugins/orangehrmAdminPlugin/test/Api/WorkShiftEmployeeAPITest.php
src/plugins/orangehrmAdminPlugin/test/fixtures/WorkShiftEmployeeAPI.yaml
src/plugins/orangehrmAdminPlugin/test/fixtures/testcases/WorkShiftEmployeeTestCases.yaml
src/plugins/orangehrmPimPlugin/Dao/EmployeeDao.php

OHRM5X-2559: Fix upgrader - 4.3.3 migration failure
